### ISSUE TITLE
Is it possible to perform DIVA gridding along isopycnals?

### ISSUE THREAD

**Issue by leopenausa** [gher-ulg/DIVA#13]
I have used ODV DIVA gridding capabilities and when a density field is available it is possible to perform an isopycnal gridding using DIVA.
Can this be done from code? I am running DIVA on python, either through the python script or calling the fortran code, but I cannot figure out how to perform isopycnal gridding. Could this be done with some implementation of the advection/difusion field?

Thanks!

**Comment by jmbeckers** [comment]
Hi,
Unfortunately there is no "ready to use" implementation for isopycnal interpolation here. 
As we will not develop further the Fortran version it is probably the easiest to stay within ODV to perform your isoycnal analysis. If you are ready to invest some time because you want some more features, you could indeed try to exploit the advection constraint but in that case I would strongly advise to move to the new DIVAnd version https://github.com/gher-ulg/divand.jl which is actively developed (and maybe we can help you out if you explain which type of data you have)
